### ISSUE TITLE
Use ifdef instead of redeficition of cudaStream_t

### ISSUE THREAD

**Issue by wentasah** [CTU-IIG/kcf#12]
Here https://github.com/Shanigen/kcf/blob/aa8977213b52ab636b354b8352fdaa2b8a6dcc99/src/scale_vars.hpp#L174 and here https://github.com/Shanigen/kcf/blob/aa8977213b52ab636b354b8352fdaa2b8a6dcc99/src/scale_vars.hpp#L10.

**Comment by Shanigen** [comment]
The redefinition of cudaStream_t is there to reduce number of ifdefs in kcf, like [here](https://github.com/Shanigen/kcf/blob/dbcc998c7f4da323e1adf3f61752e006c3787b94/src/kcf.cpp#L221) and [here](https://github.com/Shanigen/kcf/blob/dbcc998c7f4da323e1adf3f61752e006c3787b94/src/kcf.cpp#L475) for example.
