### ISSUE TITLE
Do model_xf and yf really belong to scale_vars?

### ISSUE THREAD

**Issue by wentasah** [CTU-IIG/kcf#14]
The fact that you need it only in [one instance](https://github.com/Shanigen/kcf/blob/aa8977213b52ab636b354b8352fdaa2b8a6dcc99/src/kcf.cpp#L152) suggests that it should not be there, but perhaps only in the Kcf class.

**Comment by Shanigen** [comment]
It was resolved in this commit dbcc998c7f4da323e1adf3f61752e006c3787b94.
