### ISSUE TITLE
KCF_Tracker::get_features should get features and not more 

### ISSUE THREAD

**Issue by wentasah** [CTU-IIG/kcf#2]
I'm trying to figure out why I get a segfault and [KCF_Tracker::get_features](https://github.com/Shanigen/kcf/blob/b2aae5996f155ffac62e60fa12561d7c2096a451/src/kcf.cpp#L463) confuses me. This function should only get the features not do scaling and rotation. I think that if you put scaling and roation to a separate function and keep get_features doing what its name says, the code will be much easier to read.

**Comment by Shanigen** [comment]
I have added [KCF_Tracker::geometric_transformations](https://github.com/Shanigen/kcf/blob/7c682ed29bfd43da46e6abcaf2d8b5bcaea184fd/src/kcf.cpp#L787), which should make the code easier to read and understand.

**Comment by Shanigen** [comment]
`KCF_Tracker::geometric_transformations` is no longer part of the `KCF_Tracker::get_features` and instead is together with 'KCF_Tracker::get_subwindow' performed prior to calling `KCF_Tracker::get_features`.

**Comment by wentasah** [comment]
I still don't understand why there are both `size_x/y` and `scale` parameters. I think `scale` is redundant. Also the name of `search` parameter looks confusing. Perhaps it should be named `allow_debug`?

**Comment by Shanigen** [comment]
I left the `scale` parameter there for the `m_visual_debug` part. But following your recommendations I removed it and visual debug part is now performed [outside the function](https://github.com/Shanigen/kcf/blob/6c16556f0b5a64b28d65a4c8994347270e32d1f4/src/kcf.cpp#L412). I also renamed the `search` parameter to `allow_debug` as you suggested.
