### ISSUE TITLE
Tracker fails, when performing extraction of HOG features during training

### ISSUE THREAD

**Issue by Shanigen** [CTU-IIG/kcf#28]
The tracker after finding the maximum response fails during the training of the filter. The problem is during the extraction of HOG features in [gradMag](https://github.com/wentasah/kcf/blob/bf9febfb912a43640accbc1349464208c0da6c74/src/piotr_fhog/fhog.hpp#L53) in FHoG::extract. During my testing I found out that the exact place, where the problem is, is [here](https://github.com/wentasah/kcf/blob/bf9febfb912a43640accbc1349464208c0da6c74/src/piotr_fhog/gradientMex.cpp#L92).

**Comment by wentasah** [comment]
I think I've already fixed this in commit bf9febfb912a43640accbc1349464208c0da6c74. Can you test it?

**Comment by Shanigen** [comment]
I ran the testing on your last commit, which is the one you mentioned.
