### ISSUE TITLE
Unhelpful error message

### ISSUE THREAD

**Issue by wentasah** [CTU-IIG/kcf#3]
I'm trying `cufft` version on TX2. When I run `./kcf_vot -v ~/dataset/bag/` it gives me the following error:

    Image dimension after forward FFT are too big for CUDA kernels.

If that means that I should use the `-f` option, please add it to the error message.

**Comment by Shanigen** [comment]
I added much more [verbose error message](https://github.com/Shanigen/kcf/blob/3af15bbc01deaa595f32894f432f6db149f484db/src/kcf.cpp#L136), which should help more.

**Comment by wentasah** [comment]
What does it mean "its size is less 1024 pixels". Does it mean that width×height is less than 1024?

**Comment by Shanigen** [comment]
Yes, that is exactly what it means. Should I rephrase it?

**Comment by wentasah** [comment]
That's strange. When I just add `-f`, which should be the same as `-f128x128` (i.e. 16384 pixels), the error message disappears. So something is wrong here.

**Comment by Shanigen** [comment]
But 128x128 is the size of the window before the FFT and the HOG, after the HOG and the FFT the window in the frequency domain is only 32x17, which is 544 pixels. The error message tells you that. The CUDA kernels are in the frequency domain.

**Comment by wentasah** [comment]
The original message told me "after forward FFT" and FFT does not change the size. But even if it does, the user might not be familiar with all internals of the software. The error message should tell the user how to make it work, not explain some internals of the software.

If I'm not mistaken, each HOG cell is 16 pixels and FFT cuts the size to half. So can you put there something like "Please use -f option with W*H < 32769" (i.e. 1024*16*2+1 = limit * HOGsize * FFTreduction + 1 to use < instead of <=)?

**Comment by Shanigen** [comment]
I have changed the [error message](https://github.com/Shanigen/kcf/blob/b6b99c04b0e153d4317964896ded28c868175c1f/src/kcf.cpp#L137) so its tells the user how to correct the error and also made other error message for dimensions that are not divisible by HOG cell size also [more clear](https://github.com/Shanigen/kcf/blob/9f66c16d879448fc02751529d548cfca23353b56/src/kcf.cpp#L100).
